CCI Tags example
mitre/heimdall-lite pull request #208
Opened 2020-04-09 01:00 UTC by aaronlippold

added badly formed cci tags

Real implementation needs to not use a v-if inside a v-for but use a computed property to filter out unwanted data. 

Signed-off-by: Aaron Lippold <lippold@gmail.com>

2020-04-09 16:34 UTC, Mitriol approved these changes

2020-04-10 22:34 UTC, aaronlippold commented on src/components/cards/controltable/ControlRowHeader.vue
> +      let ignored = /Rev_\d/;
This doesn't seem to be removing the Rev_4 item from the array

2020-07-07 17:18 UTC, aaronlippold commented
We need to do a rebase of these PRs to keep things clean

2020-07-07 17:19 UTC, aaronlippold commented
@cjbuchanan @Mitriol please note the attached .zip file and npm package that was pushed as an example. We may be able to borrow from there?

2020-07-15 15:44 UTC, rbclark requested changes
Additionally, there are 2 binary files included in this PR that don't seem to be used anywhere, `heimdall-logo.sketch` and a large 9MB `old-info.tar.gz` which if merged would add 9MB to every download of the repo.

2020-07-15 15:44 UTC, rbclark commented on tests/scripts/make-all.sh.broken
> +
This file seems unnecessary as part of the PR, or accidental.

2020-07-15 15:44 UTC, rbclark commented on src/components/cards/controltable/ControlRowHeader.vue
> +    }
This function can probably be replaced with 

```
return [].concat(this._control.hdf.wraps.tags.cci || []);
```

2020-07-15 15:44 UTC, rbclark commented on tests/backups/info-logs/test.log
> +../raw_data/71859-71861-71863.json
Was this log file intentionally included? It looks like an attempt was made to ignore log files above.

2020-07-15 15:44 UTC, rbclark commented on tests/scripts/make-info.sh
> +ls $INFO_PATH/*.json | sort | xargs -I $$$ sh -c "echo $$$ ; inspec_tools summary -j $$$ -o $$$.info; test -f $$$.info ; echo .info created for $$$ ; continue" | tee $LOG.log
These files are placed in the `tests/` folder but I don't see any automated testing being done that is using these files.

2020-07-15 15:44 UTC, rbclark commented on tests/scripts/make-counts.sh
> +ls $INFO_PATH/*.info | xargs -I {} sh -c "cat {} | jq .status > {}.counts" | tee $LOG.log
These files are placed in the `tests/` folder but I don't see any automated testing being done that is using these files.

2020-07-15 16:31 UTC, cjdoherty commented
This is the wrong branch, the new one is cci-tooltips-final

2020-07-29 19:16 UTC, closed without merging