Integration tests
mitre/heimdall-lite pull request #275
Opened 2020-07-03 17:43 UTC by aaronlippold

- [ ] outline the goals of the tests here

2020-07-06 19:10 UTC, Bialogs requested changes

2020-07-06 19:10 UTC, Bialogs commented on .github/workflows/docker-image.yml
> +      run: docker run -e POSTGRES_PASSWORD=testpassword -e POSTGRES_USER=testuser -e POSTGRES_DB=heimdall -p 5432:5432 -d postgres
This should be a GitHub Actions service container instead of starting docker on the runner. See: https://docs.github.com/en/actions/configuring-and-managing-workflows/about-service-containers

2020-07-06 19:10 UTC, Bialogs commented on .github/workflows/docker-image.yml
> +    - name: check file
what is the point of this

2020-07-06 19:10 UTC, Bialogs commented on .github/workflows/docker-image.yml
> +    - name: check file
What is the point of this

2020-07-06 19:10 UTC, Bialogs commented on .github/workflows/docker-image.yml
> +      run: sleep 120
We really need to add two minutes to every CI run to wait for a server to start? Also the name of the step and the command do not match.

2020-07-06 19:10 UTC, Bialogs commented on .github/workflows/docker-image.yml
> +      run: curl http://localhost:8080
what is the point of this step?

2020-07-06 19:10 UTC, Bialogs commented on tests/integration/Sample.spec.ts
> +describe("Google", () => {
Why is everything placed in a describe block named "Google"??

2020-07-06 19:10 UTC, Bialogs commented on tests/integration/Sample.spec.ts
> +import "expect-puppeteer";
Why is this file named as a Sample

2020-07-06 19:10 UTC, Bialogs commented on jest.config.integration.js
> +  preset: "./Preset.js",
Any reason the `'jest-puppeteer'` preset does not work?

2020-07-06 19:10 UTC, Bialogs commented on tests/setup.ts
> +jest.setTimeout(30000);
This seems excessive

2020-07-06 19:10 UTC, Bialogs commented on tests/integration/Sample.spec.ts
> +import "expect-puppeteer";
Most of these tests really don't assert anything, they just perform actions. What are you *testing*?

2020-07-06 19:10 UTC, Bialogs commented on tests/integration/Sample.spec.ts
> +import "expect-puppeteer";
This file has a lot of commented out cruft

2020-07-06 19:12 UTC, Bialogs requested changes

2020-07-06 19:12 UTC, Bialogs commented on tests/integration/Sample.spec.ts
> +import "expect-puppeteer";
As you can see from the run that failed in CI, the individual `it` statements depend on each other. This entire workflow should really be separated into a variety of tests/files around 1) Register 2) Sign in 3) Using the samples 4) uploading own files

2020-08-04 17:39 UTC, rbclark commented
Superseeded by https://github.com/mitre/heimdall2/pull/36

2020-08-04 17:39 UTC, closed without merging