Cci tooltips final
mitre/heimdall-lite pull request #286
Opened 2020-07-15 16:33 UTC by cjdoherty

Final version of cci-tags pr: https://github.com/mitre/heimdall-lite/pull/208

2020-07-15 18:40 UTC, aaronlippold commented
Looks like this is failing CI

2020-07-15 21:54 UTC, aaronlippold commented
Please pull in the changes and resolve the checkboxes here: https://github.com/mitre/heimdall-lite/pull/208/files
Please link the 800-53 controls to this source of the Family tag - https://nvd.nist.gov/800-53/Rev4

2020-07-23 14:43 UTC, aaronlippold commented on src/components/cards/controltable/ControlRowHeader.vue
> +    nist_tags = nist_tags.filter(tag => tag.search(/Rev.*\d/i) != 0);
Is this working as expected. Rev_4 is still showing in the tags list

2020-07-23 14:47 UTC, aaronlippold commented on src/components/cards/controltable/ResponsiveRowLarge.vue
>          <slot name="tags" />
This slot needs to be updated to change the column title to : `NIST SP 800-53 Security Controls & CCIs`

2020-07-24 23:24 UTC, rbclark requested changes

2020-07-24 23:24 UTC, rbclark commented on src/store/status_counts.ts
> +    totalTests: 0
The format of these variables is inconsistent and switches from PascalCase to LowerCamelCase. It would be best to unify these into 1 format.

2020-07-24 23:24 UTC, rbclark commented on src/store/status_counts.ts
> +  }
These functions are all exactly the same, can we just have a `filterTests() : (filter: Filter, type: String)` that just passes the type in?

2020-07-27 22:54 UTC, rbclark commented on src/store/status_counts.ts
> +  }
Can all of these methods now be deleted since they are no longer used?

2020-07-28 19:41 UTC, rbclark approved these changes

2020-07-28 19:53 UTC, aaronlippold commented
Please sign your last commit with a 
`git  co branch`
`git commit --amend -s`
`git push`

2020-07-29 19:16 UTC, merged